### ISSUE TITLE
does not work with globally installed phpstan

### ISSUE THREAD

**Issue by flip111** [szepeviktor/phpstan-wordpress#13]
I have phpstan installed with `composer global require phpstan/phpstan`

My config file is this
```neon
includes:
  - phar://phpstan.phar/conf/bleedingEdge.neon
  - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
  level: max
  inferPrivatePropertyTypeFromConstructor: true
  excludes_analyse:
    - vendor/*
    - templates
  paths:
    - .
    - libs
  autoload_files:
    - cubepoints.php
    - feed.php
    - schreikasten.php
    - uninstall.php
  autoload_directories:
    - libs
```

Then i get this error
```
Autoload file /home/flip111/.config/composer/vendor/phpstan/phpstan/../../php-stubs/wordpress-stubs/wordpress-stubs.php does not exist.
```

**Comment by szepeviktor** [comment]
Yes, phpstan-wordpress expects itself and core stubs beside PHPStan
https://github.com/szepeviktor/phpstan-wordpress/blob/master/extension.neon#L28

**Comment by szepeviktor** [comment]
You could go two ways.

1. install `szepeviktor/phpstan-wordpress` globally
1. copy `vendor/szepeviktor/phpstan-wordpress/extension.neon` and modify the paths in it

**Comment by flip111** [comment]
Maybe `%rootDir%` can be changed to `%dir_where_phpstan_config_file_is%` ? And then make path `%dir_where_phpstan_config_file_is%/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php`

**Comment by szepeviktor** [comment]
Yes, that is a third way.

**Comment by szepeviktor** [comment]
@flip111 Actually when you require `szepeviktor/phpstan-wordpress` locally it will grab PHPStan too!

So you are free to issue `vendor/bin/phpstan analyze`

**Comment by flip111** [comment]
> Yes, that is a third way.

I made up this variable `%dir_where_phpstan_config_file_is%` it probably doesn't exist. Do you know where `%rootDir%` is defined? Then i could have a look in the code if other variables for paths are also defined.

**Comment by szepeviktor** [comment]
A quick search in phpstan/phpstan-src shows https://github.com/phpstan/phpstan-src/blob/37c29d575ad293e97d3c068da008d8238b9826fa/src/DependencyInjection/ContainerFactory.php#L31-L39

**Comment by szepeviktor** [comment]
> %dir_where_phpstan_config_file_is%

AFAIK simply removing absolute path makes it relative to the configuration file itself :)

```yaml
parameters:
    autoload_files:
        - %rootDir%/../../php-stubs/wordpress-stubs/wordpress-stubs.php
        - %rootDir%/../../szepeviktor/phpstan-wordpress/bootstrap.php
```

becomes:

```yaml
parameters:
    autoload_files:
        - ../../php-stubs/wordpress-stubs/wordpress-stubs.php
        - bootstrap.php
```
