### ISSUE TITLE
Missing global constants

### ISSUE THREAD

**Issue by Mte90** [szepeviktor/phpstan-wordpress#15]
You can see on https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/ that don't find the `WP_PLUGIN_DIR` https://codex.wordpress.org/Determining_Plugin_and_Content_Directories

**Comment by szepeviktor** [comment]
Yes, I see.

> These should not be used directly by plugins or themes

As core does not provide a function for it, you should define it in `tests/phpstan/bootstrap.php` an autoload it

```yaml
parameters:
    autoload_files:
        - tests/phpstan/bootstrap.php
```

Is it okay for you?
