### ISSUE TITLE
Access to an undefined property WP_Post_Type::$template_lock

### ISSUE THREAD

**Issue by leoloso** [szepeviktor/phpstan-wordpress#19]
In level 2, this code:

```php
$post_type_object = \get_post_type_object("my-cpt");
$post_type_object->template_lock = 'all';
```

is throwing this error:

```
Access to an undefined property WP_Post_Type::$template_lock.
```

This property is documented here: https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#locking

Should this be already handled by `phpstan-wordpress`?

**Comment by szepeviktor** [comment]
Hello Leonardo! Thank you for your report!

WordPress core _forgot about_ defining this property in `WP_Post_Type` :)
https://developer.wordpress.org/reference/classes/wp_post_type/
`template_lock` is simple checked in `wp-admin/edit-form-blocks.php`

Please consider opening a new ticket about it at https://core.trac.wordpress.org/ :)

**Comment by leoloso** [comment]
OK!

**Comment by szepeviktor** [comment]
MEanwhile

```yaml
parameters:
    ignoreErrors:
        - '#^Access to an undefined property WP_Post_Type::\$template_lock\.$#'

```
